const adventEls = [


  {id: 0,
    optionText: "Can you go out and play?",
    optionOne: "",
    optionTwo: "Start Game",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 1,
    optionThreeResult: "",
    imageEl:"",
    audioAd: "",
  },

  {id: 1,
    optionText: "You're watching your favorite team, The Strangers, play against a tough team, The Boilers. Lately, The Strangers haven't been performing well, and you're fed up with their lackluster play. As you shout commands like 'SHOOT THE PUCK!!', 'PASS THE PUCK', 'HIT HIM!!' at your TV, the wind in your house picks up, the TV volume maxes out, and you find yourself sucked into the TV! Now, you're in the shoes of your favorite player, Artemi Breadman, skating to the faceoff circle...",
    optionOne: "Freak out and get off the ice",
    optionTwo: "",
    optionThree: "Show the world you can win the game",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: 3,
    imageEl: "https://img.freepik.com/premium-photo/back-view-excitement-man-with-gesturing-hands-up-how-watching-ice-hockey-television-home-rear-view-male-watching-sport-tv-excited-fan-is-rooting-his-favorite-team_431724-1795.jpg",
    audioAd: "wind"
  },


  {id: 2,
    optionText: "You lose! Try again?!",
    optionOne: "",
    optionTwo: "Try again",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 0,
    optionThreeResult: "",
    imageEl: "https://popculturehasaids.files.wordpress.com/2011/08/fans_boo.jpg",
    audioAd: "booo"
  },
  
  {id: 3,
    optionText: "You're a winger on the defensive zone faceoff. Your teammate, Pika Zibangerman, wins the faceoff and you end up with the puck. What do you do?",
    optionOne: "Skate towards the offensive zone",
    optionTwo: "Hit the puck as hard as you can into the offensive zone",
    optionThree: "Pass the puck to your goalie",
    optionOneResult: 4,
    optionTwoResult: 5,
    optionThreeResult: 6,
    imageEl: "https://media.giphy.com/media/dXu9UXIP5EQKvphTWP/giphy.gif",
    audioAd: "gameplay"
  },
  
  {id: 4,
    optionText: "You've carried the puck out of your defensive zone. What should you do now?",
    optionOne: "Dump the puck in your offensive zone",
    optionTwo: "Drive to the net",
    optionThree: "Pass the puck to your teammate",
    optionOneResult: 7,
    optionTwoResult: 8,
    optionThreeResult: 9,
    imageEl: "https://media.giphy.com/media/26BnaWZM4lg6OT4Ag/giphy.gif",
    audioAd: "boo"
  },
    
  {id: 5,
    optionText: "Oh no! You iced the puck! Now you have to start over in your zone!",
    optionOne: "",
    optionTwo: "Oops! Won't do that again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://busyplayinghockey.com/wp-content/uploads/2019/05/Icing_in_hockey.png",
    audioAd: "boo"
  },
  
  {id: 6,
    optionText: "Oh no! Your goalie didn't expect a pass from you! Thankfully, your goalie was able to recover the puck for a faceoff.",
    optionOne: "",
    optionTwo: "I won't do that again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/491AZ4PncD0BWqwJ8f/giphy.gif",
    audioAd: "boo"
  }, 

  {id: 7,
    optionText: "After dumping the puck in, Pika Zibangerman and Leo Drainstyle start to battle at the boards to get possession. Now, you should...",
    optionOne: "Go help your teamate",
    optionTwo: "Wait in front of the net for an easy goal",
    optionThree: "Start chirping at the other team's player",
    optionOneResult: 10,
    optionTwoResult: 11,
    optionThreeResult: 12,
    imageEl: "https://media.giphy.com/media/ukQsndSuXIP1zqsQdv/giphy.gif",
    audioAd: "gameplay"
  }, 

  {id: 8,
    optionText: "While driving to the net, the other team's defensive player, Pattias Elkholm, levels you to the ground. His shoulder cracks your sternum, and while falling, you hit your head hard on the ice, getting a concussion. You get stretchered off the ice. Maybe try again?",
    optionOne: "",
    optionTwo: "I'll keep my head up next time!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/3ohhwwA9ZoxCEQZVEk/giphy.gif",
    audioAd: "biggerhit"
  }, 

  {id: 9,
    optionText: "Your pass gets intercepted by Konnor MacDave! The other team develops an odd-man rush and scores a beautiful goal to win the game! Want to play again?",
    optionOne: "",
    optionTwo: "I'll make a better pass next time!",      
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/1rK4G0vp2LAdbHFKkD/giphy.gif",
    audioAd: "interception"
  }, 

  {id: 10,
    optionText: "Because you helped Maapo Mammo, you were able to get possession of the puck! Now you should...",
    optionOne: "Start the play from behind the net",
    optionTwo: "Start the play from the blue line",
    optionThree: "Pass the puck to your teammate in front of the net",
    optionOneResult: 13,
    optionTwoResult: 14,
    optionThreeResult: 15,
    imageEl: "https://www.sportsnet.ca/wp-content/uploads/2023/03/Washington-Capitals-left-wing-Alex-Ovechkin-1040x572.jpg",
    audioAd: "gameplay"
  },
  
  {id: 11,
    optionText: "You get the pass from Pika Zibangerman and take a beautiful one-timer shot to the open net but the other team's goalie makes a beautiful glove save. Now you're taking an offensive zone faceoff. You make a play with Pika Zibangerman, what do you decide?",
    optionOne: "Rush the faceoff to get possession and start the play behind the net",
    optionTwo: "Try to win the faceoff behind so that you can take a shot at the net",
    optionThree: "Try to win the faceoff behind so that your defenseman can start the play from the blueline",
    optionOneResult: 16,
    optionTwoResult: 17,
    optionThreeResult: 18, 
    imageEl: "https://media.giphy.com/media/1AfbDwOLLJk5hps1U6/giphy.gif",
    audioAd: "zibbreadshotsave"
  },

  {id: 12,
    optionText: "The other team's enforcer notices you chirping at their star player. Because he doesn't tolerate this behavior towards his teammates, he initiates a fight and drops his gloves. In a panic, you do so as well. You hold your own for a little while, but an eventual uppercut knocks you out, and you exit the game!",
    optionOne: "",
    optionTwo: "I have to pick my fights better!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/BKB2KMP7pd2RbfABAp/giphy.gif",
    audioAd: "chirp"
  },

  {id: 13,
    optionText: "As you're skating behind the net, you get leveled by Pattias Elkholm, but Pika Zibangerman is able to retrieve the loose puck! You hurry to your feet and...",
    optionOne: "Wait for the pass back behind the net",
    optionTwo: "",
    optionThree: "Skate to the front of the net for a shot",
    optionOneResult: 19,
    optionTwoResult: "",
    optionThreeResult: 20,
    imageEl: "https://media.giphy.com/media/3oKIPdpG2W7IWPppks/giphy.gif",
    audioAd: "hit"
  },

  {id: 14,
    optionText: "You pass the puck to Atom Foxy. He takes the shot and SCORES! STRANGERS WIN! STRANGERS WIN!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/mRDrjuGkvk1beE9AX8/giphy.gif",
    audioAd: "horn"
  },
  
  {id: 15,
    optionText: "You pass to Maapo Mammo for the shot, but the goalie makes a lucky save. The puck rebounds out, and Pika Zibangerman gets the rebound. Now you...",
    optionOne: "Skate behind the net for the pass",
    optionTwo: "",
    optionThree: "Skate to the front of the net for the shot",
    optionOneResult: 19,
    optionTwoResult: "",
    optionThreeResult: 20,
    imageEl: "https://media.giphy.com/media/3o6ozGDBOpMj54P2lq/giphy.gif",
    audioAd: "shotsave"
  }, 
      
  {id: 16,
    optionText: "Pika Zibangerman ties the faceoff and gives you enough time to handle the puck and skate behind the net. You scan the ice and you..",
    optionOne: "Pass the puck up to Atom Foxy at the blue line for him to shoot",
    optionTwo: "Crash the net",
    optionThree: "Pass to Maapo Mammo for the shot",
    optionOneResult: 14,
    optionTwoResult: 22,
    optionThreeResult: 21,
    imageEl: "https://media.giphy.com/media/EskuWX8kQYPAiXL3DR/giphy.gif",
    audioAd: "gameplay"
  },

  {id: 17,
    optionText: "Pika Zibangerman wins the faceoff clean to you. You take the shot and SCORE!!! YOU WON THE GAME!!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/dXi5Q5sOkD96G25dgH/giphy.gif",
    audioAd: "gameplay"
  },

  {id: 18,
    optionText: "Pika Zibangerman wins a contested faceoff with your help. You pass the puck to Atom Foxy, who takes the shot, but the goalie makes a beautiful save! Pika Zibangerman is able to get the rebound and is looking to make a play...",
    optionOne: "You wave your stick over to Maapo Mammo to take the shot",
    optionTwo: "",
    optionThree: "You call for the puck to take the shot",
    optionOneResult: 21,
    optionTwoResult: "",
    optionThreeResult: 20,
    imageEl: "https://media.giphy.com/media/l0IyhAWHXXrngHjI4/giphy.gif",
    audioAd: "shotsave"
  },

  {id: 19,
    optionText: "You call for the puck, and Pika passes it to you. You scan the ice and decide to...",
    optionOne: "Pass to Atom Foxy at the blue line for a shot",
    optionTwo: "",
    optionThree: "Go for the wrap around goal",
    optionOneResult: 9,
    optionTwoResult: "",
    optionThreeResult: 22,
    imageEl: "https://dims.apnews.com/dims4/default/7e35366/2147483647/strip/true/crop/3000x1999+0+0/resize/599x399!/quality/90/?url=https%3A%2F%2Fstorage.googleapis.com%2Fafs-prod%2Fmedia%2Fc4b8591c986d42f19417f58cf46f6879%2F3000.jpeg",
    audioAd: "gameplay"
  },

  {id: 20,
    optionText: "You take the shot and SCORE! YOU WON THE GAME!!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/fXzvDjzPwksfTHCVoH/giphy.gif",
    audioAd: "gameplay"
  },

  {id: 21,
    optionText: "Maapo Mammo takes the shot and SCORES! Great offensive play all around! YOU WON THE GAME!!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/XF22BxEpfKEy6ZvGl4/giphy.gif",
    audioAd: "horn"
  },

  {id: 22,
    optionText: "An aggressive play and it pays off! You score the goal as the puck slowly goes past the line without the goalie noticing! YOU WON THE GAME!!",
    optionOne: "",
    optionTwo: "I can do that again",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 3,
    optionThreeResult: "",
    imageEl: "https://media.giphy.com/media/hk9t99FZREzsYo0eOs/giphy.gif",
    audioAd: "wrapgoal"
  },   
]


  export {
    adventEls
  }

  