const adventEls = [

  {id: 0,
  optionText: "You're watching your favorite team, The Strangers, play against a tough team, The Boilers. The Strangers haven't been playing great the past few days and you're sick and tired of their lackluster performance. Throughout the whole game, you begin to scream at your TV 'SHOOT THE PUCK!!', 'PASS THE PUCK', 'HIT HIM!!' until suddenly, the wind picks up in your house, the TV voulme goes on full blast and you get sucked into the TV! You're playing as your favorite player, Artemi Breadman, and are skating to the faceoff circle...",
  optionOne: "Freak out and get off the ice",
  optionTwo: "Show the world you can win the game",
  optionThree: "Accept your fait but be nervous about your performance",
  optionOneResult: 1,
  optionTwoResult: 2,
  optionThreeResult: "",
  imageEl: https://www.brandonsun.com/wp-content/uploads/sites/3/2023/02/1173189_web1_BWK-Bedard-1.jpg,
  },


  {id: 1,
    optionText: "You lose! Have the confidence to play!",
    optionOne: "Wait! I have the confidence to play!",
    optionTwo: "",
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
    },
  
  {id: 2,
    optionText: "You're a winger on the defensive zone faceoff, your teammate wins the faceoff and you end up with the puck, what do you do?",
    optionOne: "Skate towards the offensive zone",
    optionTwo: "Hit the puck as hard as you can into the offensive zone",
    optionThree: "Pass the puck to your goalie",
    optionOneResult: 3,
    optionTwoResult: 4,
    optionThreeResult: 5,
    },
  
  {id: 3,
    optionText: "You carried the puck out of your defensive zone, what should you do now?",
    optionOne: "Dump the puck in your offensive zone",
    optionTwo: "Drive to the net",
    optionThree: "Pass the puck to your teammate",
    optionOneResult: 6,
    optionTwoResult: 7,
    optionThreeResult: 8,
    },
  
    
  {id: 4,
    optionText: "Oh no! You iced the puck! Now you have to start over in your zone",
    optionOne: "Oops! Won't do that again!",
    optionTwo: "",
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
    },
  
  {id: 5,
    optionText: "Oh no! youre goalie didn't expect a pass from you! Thankfully your goalie was able to recover the puck for a faceoff",
    optionElOne: "Won't do that again!",
    optionElTwo: "",
    optionElThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
      }, 

  {id: 6,
    optionText: "After dumping the puck in, your teammate and opponent start to battle at the boards to get possesion, now you should...",
    optionOne: "Go help your teamate",
    optionTwo: "Wait in front of the net for an easy goal",
    optionThree: "Start chirping at the other teams player",
    optionOneResult: 9,
    optionTwoResult: 10,
    optionThreeResult: 11,
    }, 

  {id: 7,
    optionText: "While driving to the net, the other teams defenisve player levels you to the ground. The players shoulder cracks your sternum and while falling you hit your head hard on the ice and get a concussion. You get stretchered off the ice. Maybe try again?",
    optionOne: "I'll keep my head up this time!",
    optionTwo: "",
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
    }, 
    //add a restart button and audio for hit

  {id: 8,
    optionText: "Your pass gets intercepted! The other team develops an odd man rush and gets a beautiful goal to win the game! bad pass, play again?",
    optionOne: "I'll make a better pass next time!",
    optionTwo: "",      
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
      }, 

  {id: 9,
    optionText: "Because you helped your teammate, you were able to get possession of the puck! Now you should...",
    optionOne: "Start the play from behind the net",
    optionTwo: "Start the play from the blue line",
    optionThree: "Pass the puck to your teammate in front of the net",
    optionOneResult: 12,
    optionTwoResult: 13,
    optionThreeResult: 14,
      },
  
  {id: 10,
    optionText: "You get the pass from your teammate and take a beautiful one-timer shot to the open net but the other teams goalie makes a beautiful glove save. Now you're taking an offensive zone faceoff. You make a play with your teammate taking the faceoff, what do you decide?",
    optionOne: "Rush the faceoff to get possesion and start the play behind the net",
    optionTwo: "Try to win the faceoff behind so that you can take a shot at the net",
    optionThree: "Try to win the faceoff behind so that your defenseman can start the play from the blueline",
    optionOneResult: 15,
    optionTwoResult: 16,
    optionThreeResult: 17,   
      },

  {id: 11,
    optionText: "The other teams enforcer notices you chirping at their star player. Because he does'nt tolerate this behavior towards his players, he initiates a fight and drops his gloves! In a panic you do so as well. You hold your own for a little but the eventual uppercut knocks you out and you exit the game!",
    optionOne: "",
    optionTwo: "I have to pick my fights better!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 2,
    optionThreeResult: "",
  },

  {id: 12,
    optionText: "As you're skating behind the net, you get leveled by Pattias Elkholm but Pika Zibangerman was able to get the loose puck! You hurry to your feet and...",
    optionOne: "Wait for the pass back behind the net",
    optionTwo: "Skate to the front of the net for a shot",
    optionThree: "",
    optionOneResult: 18,
    optionTwoResult: 19,
    optionThreeResult: "",
  },

  {id: 13,
    optionText: "You pass the puck to Atom Foxy. He takes the shot and SCORES! STRANGER WIN! STRANGERS WIN!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 2,
    optionThreeResult: "",
      },
  
  {id: 14,
    optionText: "You pass to Maapo Mammo for the shot but the goalie makes a lucky save. The puck rebounds out and Pika Zibangerman gets the rebound. Now you...",
    optionOne: "Skate behind the net for the pass",
    optionTwo: "Skate to the front of the net for the shot",
    optionThree: "",
    optionOneResult: 18,
    optionTwoResult: 19,
    optionThreeResult: "",
      }, 
      
  {id: 15,
    optionText: "Pika Zibangerman ties the faceoff and gives you enough time to handle the puck and skate behind the net. You scan the ice and you..",
    optionOne: "pass the puck up to Atom Foxy at the blue line for him to shoot",
    optionTwo: "crash the net",
    optionThree: "pass to Maapo Mammo for the shot",
    optionOneResult: 13,
    optionTwoResult: 21,
    optionThreeResult: 20,
      },

  {id: 16,
    optionText: "Pika Zibangerman wins the faceoffs clean to you. You take the shot and SCORE!!! YOU WON THE GAME!!",
    optionOne: "",
    optionTwo: "I can win again!",
    optionThree: "",
    optionOneResult: "",
    optionTwoResult: 2,
    optionThreeResult: "",
      },

  {id: 17,
    optionText: "Pika Zibangerman wins a contested faceoff with your help. You pass the puck to Atom Foxy who takes the shot but hits the crossbar! Pika Zibangerman was able to get thee rebound and is looking to make a play...",
    optionOne: "You wave your stick over to Maapo Maamo to take the shot",
    optionTwo: "You call for the puck to take the shot",
    optionThree: "",
    optionOneResult: 20,
    optionTwoResult: 19,
    optionThreeResult: "",
      },

  {id: 18,
    optionText: "You call for the puck and Pika passes it to you. You scan the ice and decide to...",
    optionOne: "You pass to Atom Foxy at the ble line for a shot",
    optionTwo: "Go for the wrap around goal",
    optionThree: "",
    optionOneResult: 8,
    optionTwoResult: 22,
    optionThreeResult: "",
      },
  {id: 19,
    optionText: "You take the shot and SCORE! YOU WON THE GAME!!",
    optionOne: "I can win again!",
    optionTwo: "",
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
      },

  {id: 20,
    optionText: "Maapo Mammo takes the shot and SCORES! Great offensive play all around! YOU WON THE GAME",
    optionOne: "I can win again!",
    optionTwo: "",
    optionThree: "",
    optionOneResult: 2,
    optionTwoResult: "",
    optionThreeResult: "",
      },

  {id: 18,
    optionText: "You call for the puck and Pika passes it to you. You scan the ice and decide to...",
    optionOne: "You pass to Atom Foxy at the ble line for a shot",
    optionTwo: "Go for the wrap around goal",
    optionThree: "",
    optionOneResult: 8,
    optionTwoResult: 22,
    optionThreeResult: "",
      },
  ]


  export {
    adventEls
  }

  